server:
  port: 8080

# langchain4j测试模型
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-d6809f8523c840bc9f1735c544080d5a
      model-name: deepseek-v4-flash
      # 请求和响应日志
      log-requests: true
      log-responses: true
  community:
    dashscope:
      chat-model:
        api-key: sk-255506ca196b48f38e686b3e82efac58
        model-name: qwen3-max
# 日志级别配置
logging:
  level:
    root: info                       # 根级别设为 info，屏蔽掉海量 debug 细节
#    org.mongodb.driver: warn         # 单独压低 MongoDB 驱动日志（find/update 等命令明细）
#    org.springframework.test: warn   # 屏蔽 Spring 测试上下文缓存统计
#    sun.rmi: warn                    # 屏蔽 RMI/JMX 连接日志
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/chat_memory_db